server:
  port: 8088

spring:
  application:
    name: robotlife-blog
  redis:
      host: 18.182.147.149
      port: 6379
      database: 0
      lettuce:
        pool:
          max-active: 500
          max-wait: 1ms
          max-idle: 100
          min-idle: 20

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://liuyang19900520:123456@localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
